In [11]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/danofer/india-census/india-districts-census-2011.csv
/kaggle/input/datasets/danofer/india-census/india_census_housing-hlpca-full.csv
/kaggle/input/datasets/danofer/india-census/hlpca-colnames.csv
/kaggle/input/datasets/sirpunch/indian-census-data-with-geospatial-indexing/district wise centroids.csv
/kaggle/input/datasets/sirpunch/indian-census-data-with-geospatial-indexing/district wise population for year 2001 and 2011.csv
/kaggle/input/datasets/sirpunch/indian-census-data-with-geospatial-indexing/state wise centroids_2011.csv
/kaggle/input/datasets/sirpunch/indian-census-data-with-geospatial-indexing/state wise centroids_2001.csv
/kaggle/input/datasets/sirpunch/indian-census-data-with-geospatial-indexing/district wise population and centroids.csv

In [4]:
latlong=pd.read_csv('/kaggle/input/datasets/sirpunch/indian-census-data-with-geospatial-indexing/district wise centroids.csv')

In [5]:
latlong.head()

                 State         District   Latitude  Longitude
0  Andaman and Nicobar  Andaman Islands  12.382571  92.822911
1  Andaman and Nicobar  Nicobar Islands   7.835291  93.511601
2       Andhra Pradesh         Adilabad  19.284514  78.813212
3       Andhra Pradesh        Anantapur  14.312066  77.460158
4       Andhra Pradesh         Chittoor  13.331093  78.927639

In [7]:
latlong.shape

(594, 4)

In [9]:
latlong.isnull().sum()

State        0
District     0
Latitude     0
Longitude    0
dtype: int64

In [10]:
latlong.duplicated().sum()

np.int64(0)

In [13]:
census=pd.read_csv('/kaggle/input/datasets/danofer/india-census/india-districts-census-2011.csv')

In [19]:
census

,District code,State name,District name,Population,Male,Female,Literate,Male_Literate,Female_Literate,SC,...,Power_Parity_Rs_90000_150000,Power_Parity_Rs_45000_150000,Power_Parity_Rs_150000_240000,Power_Parity_Rs_240000_330000,Power_Parity_Rs_150000_330000,Power_Parity_Rs_330000_425000,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,94,588,71,101,172,74,10,84,15,1119
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,207741,127908,368,...,126,562,72,89,161,96,28,124,18,1066
2,3,JAMMU AND KASHMIR,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,...,46,122,15,22,37,20,14,34,17,242
3,4,JAMMU AND KASHMIR,Kargil,140802,77785,63017,86236,56301,29935,18,...,27,114,12,18,30,19,3,22,7,214
4,5,JAMMU AND KASHMIR,Punch,476835,251899,224936,261724,163333,98391,556,...,78,346,35,50,85,59,8,67,12,629
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,636,PONDICHERRY,Mahe,41816,19143,22673,36470,16610,19860,144,...,2316,4309,1370,838,2208,576,978,1554,1446,10027
636,637,PONDICHERRY,Karaikal,200222,97809,102413,154916,79903,75013,35348,...,1063,2408,665,340,1005,246,483,729,341,4890
637,638,ANDAMAN AND NICOBAR ISLANDS,Nicobars,36842,20727,16115,25332,15397,9935,0,...,685,1895,212,134,346,70,120,190,84,3151
638,639,ANDAMAN AND NICOBAR ISLANDS,North AND Middle Andaman,105597,54861,50736,78683,43186,35497,0,...,685,1895,212,134,346,70,120,190,84,3151
639,640,ANDAMAN AND NICOBAR ISLANDS,South Andaman,238142,127283,110859,190266,105794,84472,0,...,1371,3020,649,368,1017,265,497,762,376,5782

In [15]:
cols = ['District code','District name','Population','Male','Female','Literate','Households_with_Internet']

In [20]:
census=census[cols]

In [22]:
census

,District code,District name,Population,Male,Female,Literate,Households_with_Internet
0,1,Kupwara,870354,474190,396164,439654,762
1,2,Badgam,753745,398041,355704,335649,1999
2,3,Leh(Ladakh),133487,78971,54516,93770,574
3,4,Kargil,140802,77785,63017,86236,235
4,5,Punch,476835,251899,224936,261724,346
...,...,...,...,...,...,...,...
635,636,Mahe,41816,19143,22673,36470,574
636,637,Karaikal,200222,97809,102413,154916,1868
637,638,Nicobars,36842,20727,16115,25332,57
638,639,North AND Middle Andaman,105597,54861,50736,78683,388
639,640,South Andaman,238142,127283,110859,190266,2789

In [23]:
latlong

                   State           District   Latitude  Longitude
0    Andaman and Nicobar    Andaman Islands  12.382571  92.822911
1    Andaman and Nicobar    Nicobar Islands   7.835291  93.511601
2         Andhra Pradesh           Adilabad  19.284514  78.813212
3         Andhra Pradesh          Anantapur  14.312066  77.460158
4         Andhra Pradesh           Chittoor  13.331093  78.927639
..                   ...                ...        ...        ...
589          West Bengal  North 24 Parganas  22.062388  88.877940
590          West Bengal           Puruliya  23.254192  86.396853
591          West Bengal  South 24 Parganas  21.854428  88.445370
592          West Bengal     Uttar Dinajpur  26.044619  88.235952
593          West Bengal     West Midnapore  22.354897  87.231014

[594 rows x 4 columns]

In [38]:
final_df=latlong.merge(census,left_on='District',right_on='District name').drop(columns=['District name'])

In [39]:
final_df

,State,District,Latitude,Longitude,District code,Population,Male,Female,Literate,Households_with_Internet
0,Andhra Pradesh,Adilabad,19.284514,78.813212,532,2741239,1369597,1371642,1483347,5512
1,Andhra Pradesh,Anantapur,14.312066,77.460158,553,4081148,2064495,2016653,2310960,8606
2,Andhra Pradesh,Chittoor,13.331093,78.927639,554,4174064,2090204,2083860,2667878,13763
3,Andhra Pradesh,East Godavari,16.782718,82.243207,545,5154296,2569688,2584608,3288577,22411
4,Andhra Pradesh,Guntur,15.884926,80.586576,548,4887813,2440521,2447292,2960441,19383
...,...,...,...,...,...,...,...,...,...,...
512,West Bengal,Maldah,25.080268,88.171917,332,3988845,2051541,1937304,2086432,5357
513,West Bengal,Murshidabad,24.259507,88.168169,333,7103807,3627564,3476243,4055834,7951
514,West Bengal,Nadia,23.564110,88.582930,336,5167600,2653768,2513832,3480555,12787
515,West Bengal,Puruliya,23.254192,86.396853,340,2930115,1496996,1433119,1624905,3551
516,West Bengal,Uttar Dinajpur,26.044619,88.235952,330,3007134,1551066,1456068,1489667,2883

In [41]:
final_df['Sex ratio']=round((final_df['Female']/final_df['Male'])*100,2)

In [42]:
final_df['literacy_rate'] = round((final_df['Literate']/final_df['Population'])*100)

In [43]:
final_df.drop(columns=['Male','Female','Literate'],inplace=True)

In [44]:
final_df.to_csv('india.csv',index=False)

In [51]:
list_of_states=list(final_df['State'].unique())

In [52]:
list_of_states.insert(0,'overall India')

In [53]:
list_of_states

['overall India',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Daman and Diu',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu and Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Orissa',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Tripura',
 'Uttar Pradesh',
 'Uttaranchal',
 'West Bengal']

In [57]:
final_df.columns

Index(['State', 'District', 'Latitude', 'Longitude', 'District code',
       'Population', 'Households_with_Internet', 'Sex ratio', 'literacy_rate'],
      dtype='object')

In [59]:
sorted(final_df.columns[5:])

['Households_with_Internet', 'Population', 'Sex ratio', 'literacy_rate']

In [65]:
import plotly.express as px
fig = px.scatter_map(final_df, lat="Latitude", lon="Longitude", zoom=3,
                  map_style="carto-positron")
fig.show()